#!/usr/bin/env python3
import asyncio, html, json, re
from datetime import datetime, timezone
from pathlib import Path
from playwright.async_api import async_playwright
W,H=1080,1350
C='#F3EEE3'; K='#0A0C0B'; F='#12352B'; R='#B70C07'; L='#B7E32B'; G='#B99A5B'
ROOT=Path(__file__).resolve().parents[1]; DATA=ROOT/'data/selected_story.json'; OUT=ROOT/'output/posts'
def clean(v): return re.sub(r'\s+',' ',re.sub(r'https?://\S+','',html.unescape(str(v or '')))).strip()
def esc(v): return html.escape(clean(v),quote=True)
def punch(v,n=9,c=78):
 s=clean(v).strip(' .,:;!?—–-'); w=s.split(); o=' '.join(w[:n]).rstrip(' .,:;!?—–-'); return s if len(w)<=n and len(s)<=c else (o if len(o)<=c else o[:c].rsplit(' ',1)[0])
def support(v,n=18,c=150):
 s=clean(v); w=s.split(); s=(' '.join(w[:n]).rstrip(' .,;:')+'…') if len(w)>n else s; return s if len(s)<=c else s[:c].rsplit(' ',1)[0]+'…'
def metric(v):
 m=re.search(r'\b\d+(?:\.\d+)?\s*[xX%]\b',clean(v)); return m.group(0).replace(' ','') if m else None
def role(s,i):
 r=clean(s.get('role')).lower().replace(' ','_'); return {'interrupt':'hook','open_loop':'open','proof':'evidence','escalation':'reveal','pattern_interrupt':'interrupt','implication':'architecture','payoff':'payoff'}.get(r,['hook','open','evidence','reveal','interrupt','architecture','payoff'][i])
def srcurl(story,s):
 u=clean(s.get('asset_url') or s.get('source_url')); return u if u.startswith('http') else clean((story.get('source_story') or {}).get('url'))
def srclabel(story,s): return clean(s.get('source_label') or 'SOURCE')
CSS=f'''@page{{size:{W}px {H}px;margin:0}}*{{box-sizing:border-box}}html,body{{margin:0;width:{W}px;height:{H}px;overflow:hidden}}body{{font-family:Arial,Helvetica,sans-serif}}.s{{position:relative;width:{W}px;height:{H}px;overflow:hidden}}.meta{{position:absolute;left:54px;right:54px;top:30px;display:flex;justify-content:space-between;z-index:50;font:800 10px/1 ui-monospace,monospace;letter-spacing:1.5px;text-transform:uppercase}}.page{{border:1px solid currentColor;padding:7px 9px}}.foot{{position:absolute;left:54px;right:54px;bottom:28px;display:flex;justify-content:space-between;z-index:50;font:800 9px/1 ui-monospace,monospace;letter-spacing:1.2px;opacity:.5}}.k{{font:900 10px/1.1 ui-monospace,monospace;letter-spacing:1.8px;text-transform:uppercase}}'''
def doc(inner,i,total,dark=False):
 bg=K if dark else C; fg=C if dark else K
 return f'''<!doctype html><style>{CSS}.s{{background:{bg};color:{fg}}}</style><div class="s">{inner}<div class="meta"><span>getByteRush</span><span class="page">{i:02d} / {total:02d}</span></div><div class="foot"><span>TECH • AI • INTERNET</span><span>TESTED • EXPLAINED • REAL</span></div></div>'''
def render_inner(s,story,i,total,evidence):
 r=role(s,i); h=punch(s.get('headline')); b=support(s.get('body')); k=esc(s.get('kicker') or r); src=esc(srclabel(story,s)); acc=clean(s.get('accent_color')) or (L if r in ('hook','reveal') else F)
 if r=='hook': return f'''<div style="position:absolute;inset:0;background:{C}"><div style="position:absolute;left:54px;top:112px;width:700px;height:1065px;background:{R};color:{C};padding:46px 42px"><div style="position:absolute;inset:0;background:repeating-linear-gradient(0deg,transparent 0 53px,rgba(255,255,255,.08) 54px),repeating-linear-gradient(90deg,transparent 0 53px,rgba(255,255,255,.08) 54px)"></div><div style="position:relative"><div class="k">{k}</div><div style="margin-top:72px;font-size:105px;line-height:.77;letter-spacing:-7px;font-weight:950;max-width:610px">{esc(h)}</div><div style="margin-top:58px;max-width:510px;font-size:20px;line-height:1.08;font-weight:800">{esc(b)}</div></div><div style="position:absolute;left:42px;right:42px;bottom:36px;border-top:1px solid rgba(255,255,255,.55);padding-top:12px;font:800 9px/1 ui-monospace,monospace;letter-spacing:1px">{src}</div></div><div style="position:absolute;right:54px;top:165px;width:225px;height:845px;background:{K};color:{C};padding:25px"><div class="k" style="color:{L}">01 / SCALE</div><div style="position:absolute;right:-24px;bottom:95px;font-size:168px;line-height:.6;font-weight:950;letter-spacing:-13px;color:{acc};transform:rotate(-90deg)">{esc(metric(h) or '01')}</div><div style="position:absolute;left:25px;bottom:30px;font-size:13px;font-weight:800">SWIPE →</div></div></div>'''
 if r=='open': return f'''<div style="position:absolute;left:54px;right:54px;top:116px"><div class="k" style="color:{R}">{k}</div><div style="margin-top:15px;font-size:76px;line-height:.82;letter-spacing:-5px;font-weight:950;max-width:900px">{esc(h)}</div></div><div style="position:absolute;left:54px;right:54px;top:430px;bottom:100px"><div style="position:absolute;left:0;width:60%;height:100%;border:2px solid {K};padding:32px"><div class="k" style="opacity:.5">THE BOTTLENECK</div><div style="margin-top:54px;font-size:51px;line-height:.86;letter-spacing:-3px;font-weight:950;max-width:520px">{esc(punch(b,10,72))}</div><div style="position:absolute;right:32px;bottom:30px;font-size:110px;color:{R}">↗</div></div><div style="position:absolute;right:0;top:42px;width:36%;height:92%;background:{F};color:{C};padding:29px"><div class="k">02 / WHY IT MATTERS</div><div style="margin-top:68px;font-size:47px;line-height:.84;letter-spacing:-2.5px;font-weight:950">{esc(punch(h,7,46))}</div><div style="margin-top:25px;font-size:15px;line-height:1.18;opacity:.7">{esc(support(s.get('implication') or b,14,100))}</div></div></div>'''
 if r=='evidence':
  img=f'<img src="file://{evidence}" style="width:100%;height:100%;object-fit:contain;display:block">' if evidence else '<div style="padding:50px;font-size:30px;font-weight:900">SOURCE IMAGE UNAVAILABLE</div>'
  return f'''<div style="position:absolute;left:54px;right:54px;top:116px"><div class="k" style="color:{R}">{k}</div><div style="margin-top:14px;font-size:67px;line-height:.84;letter-spacing:-4px;font-weight:950;max-width:860px">{esc(h)}</div></div><div style="position:absolute;left:54px;right:54px;top:410px;bottom:90px"><div style="position:absolute;left:0;right:130px;top:0;height:700px;background:#fff;border:2px solid {K};padding:10px;box-shadow:22px 22px 0 {R};overflow:hidden"><span style="position:absolute;left:20px;top:20px;z-index:2;background:{R};color:{C};padding:9px 12px;font:900 9px/1 ui-monospace,monospace;letter-spacing:1.1px">VERIFIED / SOURCE</span>{img}</div><div style="position:absolute;right:0;top:60px;width:100px;font:900 9px/1.1 ui-monospace,monospace;writing-mode:vertical-rl;transform:rotate(180deg);opacity:.6">{src}</div><div style="position:absolute;left:0;bottom:0;max-width:700px;font-size:18px;line-height:1.08;font-weight:900">{esc(b)}</div></div>'''
 if r=='reveal':
  m=metric(h) or '30X'; return f'''<div style="position:absolute;inset:0;background:{K};color:{C}"><div style="position:absolute;right:-20px;top:300px;font-size:330px;line-height:.6;font-weight:950;letter-spacing:-25px;color:{acc}">{esc(m)}</div><div style="position:absolute;left:54px;top:205px;right:54px"><div class="k" style="color:{acc}">04 / {k}</div><div style="margin-top:45px;font-size:104px;line-height:.75;letter-spacing:-7px;font-weight:950;max-width:720px">{esc(h)}</div><div style="margin-top:38px;max-width:560px;font-size:19px;line-height:1.16;opacity:.72">{esc(b)}</div></div><div style="position:absolute;left:54px;bottom:76px;border-top:2px solid {acc};padding-top:10px;width:240px;font:800 9px/1.2 ui-monospace,monospace">{src}</div></div>'''
 if r=='interrupt': return f'''<div style="position:absolute;inset:0;background:{R};color:{C}"><div style="position:absolute;left:54px;right:54px;top:150px;bottom:72px;border-top:2px solid rgba(255,255,255,.55);border-bottom:2px solid rgba(255,255,255,.55)"><div style="position:absolute;right:0;top:22px;font:900 10px/1 ui-monospace,monospace">05 / PATTERN INTERRUPT</div><div style="position:absolute;left:0;top:150px;max-width:850px;font-size:112px;line-height:.73;letter-spacing:-8px;font-weight:950">{esc(h)}</div><div style="position:absolute;left:0;bottom:20px;max-width:540px;font-size:18px;line-height:1.16;opacity:.78">{esc(b)}</div><div style="position:absolute;right:-10px;bottom:-90px;font-size:300px;line-height:.6;font-weight:950;color:{K};opacity:.2">{esc(metric(h) or '×')}</div></div></div>'''
 if r=='architecture':
  vals=re.findall(r'[A-Za-z][A-Za-z0-9-]{3,}',clean(s.get('body'))+' '+clean(s.get('context'))); stop={'with','from','that','this','into','they','more','than','using','every','context','across','keep','focused'}; vals=[x for x in vals if x.lower() not in stop][:3]; vals=(vals+['CONTEXT','CACHE','REASONING'])[:3]
  return f'''<div style="position:absolute;left:54px;right:54px;top:116px"><div class="k" style="color:{R}">{k}</div><div style="margin-top:14px;font-size:72px;line-height:.82;letter-spacing:-5px;font-weight:950;max-width:900px">{esc(h)}</div></div><div style="position:absolute;left:54px;right:54px;top:450px;height:620px"><div style="position:absolute;left:0;right:0;top:175px;height:2px;background:{K};opacity:.2"></div><div style="position:absolute;left:0;width:29%;height:235px;border:2px solid {K};padding:23px"><div class="k">01 / NODE</div><div style="margin-top:48px;font-size:31px;line-height:.9;font-weight:950">{esc(vals[0].upper())}</div></div><div style="position:absolute;left:35.5%;top:110px;width:29%;height:235px;background:{F};color:{C};padding:23px"><div class="k">02 / LINK</div><div style="margin-top:48px;font-size:31px;line-height:.9;font-weight:950">{esc(vals[1].upper())}</div></div><div style="position:absolute;right:0;width:29%;height:235px;background:{R};color:{C};padding:23px"><div class="k">03 / OUTPUT</div><div style="margin-top:48px;font-size:31px;line-height:.9;font-weight:950">{esc(vals[2].upper())}</div></div><div style="position:absolute;left:0;bottom:0;max-width:760px;font-size:18px;line-height:1.16;opacity:.7">{esc(b)}</div></div>'''
 return f'''<div style="position:absolute;left:54px;right:54px;top:116px"><div class="k" style="color:{R}">{k}</div><div style="margin-top:15px;font-size:74px;line-height:.81;letter-spacing:-5px;font-weight:950;max-width:900px">{esc(h)}</div></div><div style="position:absolute;left:54px;right:54px;top:420px;bottom:100px;background:{K};color:{C};padding:55px"><div class="k" style="color:{L}">07 / THE BOTTOM LINE</div><div style="margin-top:48px;font-size:88px;line-height:.78;letter-spacing:-6px;font-weight:950;max-width:800px">{esc(h)}</div><div style="margin-top:28px;max-width:650px;font-size:18px;line-height:1.17;opacity:.7">{esc(b)}</div><div style="position:absolute;right:-25px;bottom:-80px;font-size:300px;color:{R}">→</div></div>'''
async def capture(page,url,target):
 if not url:return None
 try:
  await page.goto(url,wait_until='domcontentloaded',timeout=30000); await page.wait_for_timeout(1500); await page.add_style_tag(content='''[id*=cookie],[class*=cookie],[id*=consent],[class*=consent],[aria-label*=cookie i],[aria-label*=consent i]{display:none!important}'''); await page.screenshot(path=str(target)); return target.as_posix()
 except Exception as e: print('Evidence capture skipped:',e); return None
async def main():
 story=json.loads(DATA.read_text()); slides=story.get('slides') or []
 if not story.get('selected') or not slides: raise SystemExit('No selected editorial')
 now=datetime.now().astimezone(); slug=re.sub(r'[^a-z0-9]+','-',clean(story.get('story_title','post')).lower()).strip('-')[:72]; package=OUT/now.strftime('%Y-%m-%d')/(now.strftime('%H%M%S')+'-'+slug); sd=package/'slides'; hd=package/'html'; ed=package/'evidence'; [p.mkdir(parents=True,exist_ok=True) for p in (sd,hd,ed)]
 async with async_playwright() as pw:
  browser=await pw.chromium.launch(); ep=await browser.new_page(viewport={'width':1440,'height':1000}); rp=await browser.new_page(viewport={'width':W,'height':H}); ev=None
  for i,s in enumerate(slides):
   if role(s,i)=='evidence' and not ev: ev=await capture(ep,srcurl(story,s),ed/'source.png')
   hp=hd/f'{i+1:02d}.html'; hp.write_text(doc(render_inner(s,story,i,len(slides),ev),i+1,len(slides),role(s,i) in {'reveal','interrupt'}),encoding='utf-8'); await rp.goto(hp.as_uri(),wait_until='load'); await rp.screenshot(path=str(sd/f'{i+1:02d}.png'))
  await browser.close()
 for n,v in [('caption.txt',story.get('caption','')),('hashtags.txt',' '.join('#'+str(x).lstrip('#') for x in story.get('hashtags',[]))),('alt-text.txt',story.get('alt_text',''))]: (package/n).write_text(str(v).strip()+'\n')
 (package/'post.json').write_text(json.dumps({**story,'rendered_at':datetime.now(timezone.utc).isoformat(),'renderer':'getbyterush-pinterest-editorial-v7','gemini_calls':0},indent=2,ensure_ascii=False)+'\n')
 print('RENDERED_PACKAGE='+str(package)); print('SLIDES='+str(len(slides))); print('GEMINI_CALL=0')
if __name__=='__main__': asyncio.run(main())
