#!/usr/bin/env python3
import asyncio,html,json,re
from datetime import datetime
from pathlib import Path
from playwright.async_api import async_playwright
W,H=1080,1350
C='#F2EBDD';K='#090B0A';F='#12372C';R='#B80D08';L='#B7E32B';G='#C4A05B'
ROOT=Path(__file__).resolve().parents[1];DATA=ROOT/'data/selected_story.json';OUT=ROOT/'output/posts'
def clean(v): return re.sub(r'\s+',' ',re.sub(r'https?://\S+','',html.unescape(str(v or '')))).strip()
def esc(v): return html.escape(clean(v),quote=True)
def punch(v,n=8,c=72):
 s=clean(v).strip(' .,:;!?—–-');w=s.split()
 if len(w)<=n and len(s)<=c:return s
 x=' '.join(w[:n]).rstrip(' .,:;!?—–-');return x if len(x)<=c else x[:c].rsplit(' ',1)[0]
def support(v,n=16,c=135):
 s=clean(v);w=s.split()
 if len(w)>n:s=' '.join(w[:n]).rstrip(' .,;:')+'…'
 return s if len(s)<=c else s[:c].rsplit(' ',1)[0]+'…'
def metric(v):
 m=re.search(r'\b\d+(?:\.\d+)?\s*[xX%]\b',clean(v));return m.group(0).replace(' ','') if m else ''
def role(s,i):
 r=clean(s.get('role')).lower().replace(' ','_');return {'interrupt':'hook','open_loop':'open','proof':'evidence','escalation':'reveal','pattern_interrupt':'interrupt','implication':'architecture','payoff':'payoff'}.get(r,['hook','open','evidence','reveal','interrupt','architecture','payoff'][i])
def source_url(story,s):
 u=clean(s.get('asset_url') or s.get('source_url'));return u if u.startswith('http') else clean((story.get('source_story') or {}).get('url'))
def source_label(s):return clean(s.get('source_label') or 'SOURCE')
BASE=f'''@page{{size:{W}px {H}px;margin:0}}*{{box-sizing:border-box}}html,body{{margin:0;width:{W}px;height:{H}px;overflow:hidden}}body{{font-family:Arial,Helvetica,sans-serif}}.s{{position:relative;width:{W}px;height:{H}px;overflow:hidden}}.meta{{position:absolute;z-index:30;top:28px;left:52px;right:52px;display:flex;justify-content:space-between;font:800 10px/1 ui-monospace,monospace;letter-spacing:1.7px;text-transform:uppercase}}.page{{border:1px solid currentColor;padding:7px 9px}}.foot{{position:absolute;z-index:30;bottom:27px;left:52px;right:52px;display:flex;justify-content:space-between;font:800 9px/1 ui-monospace,monospace;letter-spacing:1.2px;opacity:.55}}.k{{font:900 10px/1 ui-monospace,monospace;letter-spacing:1.8px;text-transform:uppercase}}.grid{{background-image:linear-gradient(rgba(0,0,0,.06) 1px,transparent 1px),linear-gradient(90deg,rgba(0,0,0,.06) 1px,transparent 1px);background-size:36px 36px}}'''
def doc(inner,i,total,dark=False):
 bg=K if dark else C;fg=C if dark else K
 return f'''<!doctype html><style>{BASE}.s{{background:{bg};color:{fg}}}</style><div class="s">{inner}<div class="meta"><span>getByteRush</span><span class="page">{i:02d} / {total:02d}</span></div><div class="foot"><span>TECH • AI • INTERNET</span><span>TESTED • EXPLAINED • REAL</span></div></div>'''
def inner(s,story,i,total,evidence):
 r=role(s,i);h=punch(s.get('headline'));b=support(s.get('body'));k=esc(s.get('kicker') or r);src=esc(source_label(s));m=esc(metric(h))
 if r=='hook':
  return f'''<div class="grid" style="position:absolute;inset:0"><div style="position:absolute;left:52px;top:116px;width:650px;height:1080px;background:{R};color:{C};padding:42px"><div style="position:absolute;inset:0;background:repeating-linear-gradient(0deg,transparent 0 47px,rgba(255,255,255,.09) 48px),repeating-linear-gradient(90deg,transparent 0 47px,rgba(255,255,255,.09) 48px)"></div><div style="position:relative"><div class="k">{k}</div><div style="margin-top:76px;font-size:108px;line-height:.74;letter-spacing:-8px;font-weight:950;max-width:575px">{esc(h)}</div><div style="margin-top:58px;max-width:490px;font-size:20px;line-height:1.1;font-weight:800">{esc(b)}</div></div><div style="position:absolute;left:42px;right:42px;bottom:34px;border-top:1px solid rgba(255,255,255,.6);padding-top:11px;font:800 9px/1 ui-monospace,monospace;letter-spacing:1px">{src}</div></div><div style="position:absolute;right:52px;top:164px;width:238px;height:870px;background:{K};color:{C};padding:24px"><div class="k" style="color:{L}">01 / INTERRUPT</div><div style="position:absolute;left:23px;bottom:36px;font-size:14px;font-weight:900">SWIPE →</div><div style="position:absolute;right:-8px;top:300px;font-size:178px;line-height:.6;font-weight:950;letter-spacing:-15px;color:{L};writing-mode:vertical-rl;transform:rotate(180deg)">{m or '15X'}</div><div style="position:absolute;left:22px;bottom:110px;width:110px;height:2px;background:{R}"></div></div></div>'''
 if r=='open':
  return f'''<div style="position:absolute;left:52px;right:52px;top:112px"><div class="k" style="color:{R}">{k}</div><div style="margin-top:18px;font-size:77px;line-height:.79;letter-spacing:-5px;font-weight:950;max-width:930px">{esc(h)}</div></div><div style="position:absolute;left:52px;right:52px;top:430px;bottom:92px"><div style="position:absolute;left:0;top:38px;width:57%;height:650px;border:2px solid {K};padding:32px;background:linear-gradient(135deg,transparent 0 88%,rgba(0,0,0,.04) 88%)"><div class="k" style="opacity:.55">THE BOTTLENECK</div><div style="margin-top:58px;font-size:52px;line-height:.82;letter-spacing:-3px;font-weight:950;max-width:480px">{esc(punch(b,9,65))}</div><div style="position:absolute;right:28px;bottom:26px;font-size:112px;color:{R}">↗</div></div><div style="position:absolute;right:0;top:0;width:39%;height:735px;background:{F};color:{C};padding:30px"><div class="k" style="color:{L}">02 / WHY IT MATTERS</div><div style="margin-top:72px;font-size:49px;line-height:.82;letter-spacing:-3px;font-weight:950">{esc(punch(h,7,48))}</div><div style="position:absolute;left:30px;right:30px;bottom:34px;border-top:1px solid rgba(255,255,255,.35);padding-top:14px;font-size:15px;line-height:1.15;opacity:.75">{esc(support(s.get('implication') or b,13,100))}</div></div></div>'''
 if r=='evidence':
  image=f'<img src="file://{evidence}" style="width:100%;height:100%;object-fit:contain;display:block">' if evidence else '<div style="padding:40px;font-size:28px;font-weight:900">SOURCE UNAVAILABLE</div>'
  return f'''<div style="position:absolute;left:52px;right:52px;top:112px"><div class="k" style="color:{R}">{k}</div><div style="margin-top:15px;font-size:70px;line-height:.8;letter-spacing:-5px;font-weight:950;max-width:900px">{esc(h)}</div></div><div style="position:absolute;left:52px;right:52px;top:430px;bottom:88px"><div style="position:absolute;left:0;right:118px;top:0;height:650px;background:#fff;border:2px solid {K};padding:12px;overflow:hidden;box-shadow:24px 24px 0 {R}"><span style="position:absolute;z-index:4;left:22px;top:22px;background:{R};color:{C};padding:9px 12px;font:900 9px/1 ui-monospace,monospace;letter-spacing:1px">VERIFIED / SOURCE</span>{image}</div><div style="position:absolute;right:0;top:45px;width:82px;font:900 9px/1.1 ui-monospace,monospace;writing-mode:vertical-rl;transform:rotate(180deg);opacity:.55">{src}</div><div style="position:absolute;left:0;bottom:0;max-width:720px;font-size:18px;line-height:1.12;font-weight:900">{esc(b)}</div></div>'''
 if r=='reveal':
  return f'''<div style="position:absolute;inset:0;background:{K};color:{C}"><div style="position:absolute;left:52px;right:52px;top:120px"><div class="k" style="color:{L}">04 / {k}</div><div style="margin-top:44px;font-size:108px;line-height:.7;letter-spacing:-8px;font-weight:950;max-width:700px">{esc(h)}</div><div style="margin-top:38px;max-width:530px;font-size:18px;line-height:1.18;opacity:.72">{esc(b)}</div></div><div style="position:absolute;right:-38px;bottom:112px;font-size:330px;line-height:.55;font-weight:950;letter-spacing:-24px;color:{L}">{m or '30X'}</div><div style="position:absolute;left:52px;bottom:82px;width:250px;border-top:2px solid {L};padding-top:10px;font:800 9px/1.2 ui-monospace,monospace">{src}</div><div style="position:absolute;right:52px;top:210px;width:90px;height:90px;border:1px solid {L};border-radius:50%"></div></div>'''
 if r=='interrupt':
  return f'''<div style="position:absolute;inset:0;background:{R};color:{C}"><div style="position:absolute;left:52px;right:52px;top:138px;bottom:72px;border-top:2px solid rgba(255,255,255,.55);border-bottom:2px solid rgba(255,255,255,.55)"><div class="k" style="position:absolute;right:0;top:22px">05 / PATTERN INTERRUPT</div><div style="position:absolute;left:0;top:155px;max-width:850px;font-size:116px;line-height:.7;letter-spacing:-8px;font-weight:950">{esc(h)}</div><div style="position:absolute;left:0;bottom:20px;max-width:550px;font-size:18px;line-height:1.15;opacity:.8">{esc(b)}</div><div style="position:absolute;right:-5px;bottom:-95px;font-size:310px;line-height:.6;font-weight:950;color:{K};opacity:.2">{m or '×'}</div><div style="position:absolute;left:0;top:70px;width:125px;height:2px;background:{K}"></div></div></div>'''
 if r=='architecture':
  return f'''<div style="position:absolute;inset:0;background:{C}"><div style="position:absolute;left:52px;right:52px;top:112px"><div class="k" style="color:{R}">{k}</div><div style="margin-top:15px;font-size:75px;line-height:.8;letter-spacing:-5px;font-weight:950;max-width:900px">{esc(h)}</div></div><div style="position:absolute;left:52px;right:52px;top:455px;height:580px"><div style="position:absolute;left:0;right:0;top:116px;border-top:2px solid {K};opacity:.18"></div><div style="position:absolute;left:0;top:0;width:29%;height:230px;border:2px solid {K};padding:23px;background:{C}"><div class="k">01 / CONTEXT</div><div style="margin-top:50px;font-size:32px;line-height:.9;font-weight:950">LONG<br>CONTEXT</div></div><div style="position:absolute;left:35.5%;top:105px;width:29%;height:230px;background:{F};color:{C};padding:23px"><div class="k" style="color:{L}">02 / MEMORY</div><div style="margin-top:50px;font-size:31px;line-height:.9;font-weight:950">KV<br>CACHE</div></div><div style="position:absolute;right:0;top:0;width:29%;height:230px;background:{R};color:{C};padding:23px"><div class="k">03 / RESULT</div><div style="margin-top:50px;font-size:31px;line-height:.9;font-weight:950">FAST<br>REASONING</div></div><div style="position:absolute;left:0;bottom:0;max-width:760px;font-size:18px;line-height:1.15;opacity:.7">{esc(b)}</div><div style="position:absolute;left:29%;top:84px;font-size:30px;color:{R}">→</div><div style="position:absolute;left:64%;top:84px;font-size:30px;color:{R}">→</div></div></div>'''
 return f'''<div style="position:absolute;inset:0;background:{C}"><div style="position:absolute;left:52px;right:52px;top:112px"><div class="k" style="color:{R}">07 / THE BOTTOM LINE</div><div style="margin-top:18px;font-size:77px;line-height:.78;letter-spacing:-5px;font-weight:950;max-width:900px">{esc(h)}</div></div><div style="position:absolute;left:52px;right:52px;top:455px;height:665px;background:{K};color:{C};padding:52px;overflow:hidden"><div style="position:absolute;inset:0;background:repeating-linear-gradient(135deg,transparent 0 59px,rgba(255,255,255,.035) 60px)"></div><div style="position:relative"><div class="k" style="color:{L}">THE ERA AHEAD</div><div style="margin-top:55px;font-size:86px;line-height:.75;letter-spacing:-6px;font-weight:950;max-width:760px">{esc(h)}</div><div style="margin-top:30px;max-width:610px;font-size:18px;line-height:1.17;opacity:.72">{esc(b)}</div></div><div style="position:absolute;right:-30px;bottom:-100px;font-size:330px;line-height:.5;font-weight:950;color:{R}">→</div></div></div>'''
async def capture(page,url,target):
 if not url:return None
 try:
  await page.goto(url,wait_until='domcontentloaded',timeout=30000);await page.wait_for_timeout(1200);await page.add_style_tag(content='''[id*=cookie],[class*=cookie],[id*=consent],[class*=consent],[aria-label*=cookie i],[aria-label*=consent i]{display:none!important}''');await page.screenshot(path=str(target));return target.as_posix()
 except Exception as e: print('Evidence capture skipped:',e);return None
async def main():
 story=json.loads(DATA.read_text());slides=story.get('slides') or []
 if not story.get('selected') or not slides:raise SystemExit('No selected editorial')
 now=datetime.now().astimezone();slug=re.sub(r'[^a-z0-9]+','-',clean(story.get('story_title','post')).lower()).strip('-')[:72];pkg=OUT/now.strftime('%Y-%m-%d')/(now.strftime('%H%M%S')+'-'+slug);sd=pkg/'slides';hd=pkg/'html';ed=pkg/'evidence'
 for p in (sd,hd,ed):p.mkdir(parents=True,exist_ok=True)
 async with async_playwright() as pw:
  browser=await pw.chromium.launch();ep=await browser.new_page(viewport={'width':1440,'height':1000});rp=await browser.new_page(viewport={'width':W,'height':H});ev=None
  for i,s in enumerate(slides):
   if role(s,i)=='evidence' and not ev:ev=await capture(ep,source_url(story,s),ed/'source.png')
   hp=hd/f'{i+1:02d}.html';hp.write_text(doc(inner(s,story,i,len(slides),ev),i+1,len(slides),role(s,i) in {'reveal'}),encoding='utf-8');await rp.goto(hp.as_uri(),wait_until='load');await rp.screenshot(path=str(sd/f'{i+1:02d}.png'))
  await browser.close()
 for n,v in [('caption.txt',story.get('caption','')),('hashtags.txt',' '.join('#'+str(x).lstrip('#') for x in story.get('hashtags',[]))),('alt-text.txt',story.get('alt_text','')),('pinned-comment.txt',story.get('pinned_comment',''))]: (pkg/n).write_text(str(v or ''),encoding='utf-8')
 post=dict(story);post['renderer']='getbyterush-pinterest-editorial-v8';post['gemini_calls']=0;post['rendered_at']=datetime.now().astimezone().isoformat();(pkg/'post.json').write_text(json.dumps(post,indent=2,ensure_ascii=False),encoding='utf-8')
 print('RENDERED',pkg)
if __name__=='__main__':asyncio.run(main())
